/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void InitializeEngine(int workers);
extern char* HashPassword(char* pass, char* algo, int iterations, int memory, int parallelism);
extern int VerifyPassword(char* pass, char* hashEncoded);
extern char* GeneratePassword(int length, char* charset);
extern char* GetRandomBytes(int length);
extern long int GetRandomInt(long int max);
extern char* GenerateOTP(int digitCount);
extern char* GetHash(char* data, int length, char* algo);
extern char* GetSHA256(char* data, int length);
extern char* GetHMAC(char* key, int keyLen, char* data, int dataLen, char* algo);
extern char* HKDF(char* ikm, int ikmLen, char* salt, int saltLen, char* info, int infoLen, int outputLen);
extern char* PBKDF2(char* pass, char* salt, int saltLen, int iterations, int keyLen, char* algo);
extern int ConstantTimeCompare(char* a, int aLen, char* b, int bLen);
extern char* Encrypt(char* pass, char* key, char* algo);
extern char* Decrypt(char* encrypted, char* key, char* algo);
extern char* EncryptRaw(char* data, int dataLen, char* key, int keyLen, char* algo);
extern char* DecryptRaw(char* encrypted, char* key, char* algo, int keyLen);
extern void RunNTT(char* data);
extern int SampleLWEError();
extern char* KyberGenerateKeyPair();
extern char* GenerateX25519KeyPair();
extern char* DeriveSharedSecretX25519(char* priv, char* pub);
extern void FreeString(char* str);

#ifdef __cplusplus
}
#endif
