
export const BUFFER_SECURITY_CONSTANTS = {
    CANARY_SIZE: 16,
    ENCRYPTION_KEY_SIZE: 32,
    NONCE_SIZE: 24,
    MAC_SIZE: 16,
    FRAGMENT_SIZE: 64,
    MAX_FRAGMENTS: 256,
    OBFUSCATION_ROUNDS: 7,
    MEMORY_POISON_PATTERN: 0xdeadbeef,
} as const;
