/***************************************************************************
 * XyPriss Security - Unified Utility Hub
 *
 * @author NEHONIX (iDevo - https://github.com/iDevo-ll)
 * @license Nehonix Open Source License (NOSL)
 ****************************************************************************/

export * from "./encoding";

import { Hash, Random } from "../core/index";
import { Bridge } from "../core/bridge";

/**
 * High-performance cryptographic hashing utility.
 * Leverages the Go-backed core engine for extreme throughput and security.
 *
 * @param data - The string or byte array payload to hash.
 * @param options - Configuration options for the hashing algorithm (e.g., specific algorithms, output formats).
 * @returns The resulting cryptographic hash.
 */
export const hash = (data: string | Uint8Array, options?: any) =>
  Hash.create(data, options);

/**
 * Generates cryptographically secure random bytes.
 * Utilizing Go's native `crypto/rand` module, it ensures true randomness
 * suitable for key generation, salts, and nonces.
 *
 * @param length - The number of bytes to generate.
 * @returns A buffer-like object containing the secure random bytes.
 */
export const getRandomBytes = (length: number) => Random.getRandomBytes(length);

/**
 * Military-grade string encryption utilizing AES-256-GCM or ChaCha20-Poly1305.
 * Designed for maximum performance with atomic Go FFI calls.
 *
 * @param data - The plaintext string to encrypt.
 * @param key - The secret key used for encryption (must be properly derived and sized).
 * @param algo - The target algorithm ("aes" or "chacha20"). Defaults to "aes".
 * @returns The encrypted payload formatted as a hex-encoded `nonce:tag:ciphertext` string.
 */
export const encrypt = (data: string, key: string, algo: string = "aes") =>
  Bridge.encrypt(data, key, algo);

/**
 * High-speed string decryption utilizing AES-256-GCM or ChaCha20-Poly1305.
 * Safely decodes payloads generated by the `encrypt` utility.
 *
 * @param encrypted - The encrypted payload (must be in `nonce:tag:ciphertext` hex format).
 * @param key - The secret key used for decryption.
 * @param algo - The target algorithm ("aes" or "chacha20"). Defaults to "aes".
 * @returns The decrypted plaintext string. Throws an error if authentication logic fails.
 */
export const decrypt = (encrypted: string, key: string, algo: string = "aes") =>
  Bridge.decrypt(encrypted, key, algo);

export const Utils = {
  hash,
  getRandomBytes,
  encrypt,
  decrypt,
};
